name: API Tests
on: [push] # Тести будуть запускатися при кожному завантаженні файлів

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra
      - name: Run Tests with Report
        run: |
          newman run "Dummy_json.postman_collection.json" \
          --env-var "baseUrl=https://dummyjson.com" \
          -r htmlextra --reporter-htmlextra-export report.html

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: postman-report
          path: report.html
